name: EntityProtect
main: kr.kkiro.projects.bukkit.entityprotect.EntityProtect
version: 0.1.1
commands:
  entityprotect:
    description: EntityProtect main command
    usage: /<command>
    aliases: ep
permissions:
  entityprotect.*:
    description: Everything
    default: op
    children:
       entityprotect.get: true
       entityprotect.set: true
       entityprotect.killall: true
       entityprotect.setowner: true
       entityprotect.delowner: true
       entityprotect.finish: true
       entityprotect.bypass: true
       entityprotect.bypass.*: true
  entityprotect.bypass.*:
    description: bypass all
    children:
       entityprotect.bypass.damage: true
       entityprotect.bypass.damage1hp: true
       entityprotect.bypass.slay: true
       entityprotect.bypass.shear: true
  entityprotect.get:
    description: Get player
  entityprotect.set:
    description: Set player
  entityprotect.killall:
    description: Killall player
  entityprotect.setowner:
    description: set owner
  entityprotect.delowner:
    description: delete owner
  entityprotect.finish:
    description: finish
  entityprotect.bypass:
    description: bypass
  entityprotect.bypass.damage:
    description: bypass
  entityprotect.bypass.damage1hp:
    description: bypass
  entityprotect.bypass.slay:
    description: bypass
  entityprotect.bypass.shear:
    description: bypass