##
## EntityProtect Config File
##

config-version: 0

general:
  enabled: true
  bypass: false
  maxentity: 60

protect:
  damage: true
  breed: true
  kidnap: true
  lava: false
  drown: false
  burn: false
  fall: false

mob:
  Chicken: true
  Cow: true
  MushroomCow: true
  Pig: true
  Sheep: true
  Wolf: true
  Ozelot: true
  
environment:
  # Set owner if you breed animal.
  setowneratbreed: true
  # Prevent animal extinction.
  extinction:
    # Respawn time
    respawntime: 60
    # Respawn when killed by Environment
    kill: true
    # Respawn when slayed by Player
    slay: true
    # spawn another when natural animal get owner.
    owner: true

translation:
  mobs:
    Chicken: 'Chicken'
    Cow: 'Cow'
    MushroomCow: 'Mooshroom'
    Pig: 'Pig'
    Sheep: 'Sheep'
    Wolf: 'Wolf'
    Ozelot: 'Cat'
  info: '&bYou can now breed &a$2 &bmore animals.'
  owner: '&bThis &c$1&b\'s owner is &c$2&b.'
  owneryou: '&bThis &c$1%b\'s owner is &cYou&b.'
  breed: '&aYou breeded &c$1&a, You can now breed &b$2 &amore animals.'
  setowner: '&c$1&as that you breeded were natural animals. \nSo they now belong to you, so you can breed &b$2 &amore animals.'
  kill: '&c$1&a killed your &c$1%a. You can now breed &b$2 &amore animals.'
  killyou: '&cYou&a killed your &c$1%a. You can now breed &b$2 &amore animals.'
  permission: '&cYou don't have permission : \'&f$1&c\'.'
  
