general:
  enabled: true
  allow-bypass: false
  allow-groups: true
  allow-trading: true
  max-entities-per-player: 60
  #This plugin uses Bukkit's database, If you want to set database, edit bukkit.yml

# true = enabled if only have owners
# false = not enabled
# nonowner = enabled except owner, But unregistered entities are also enabled
protect-entities:
  damaging: false
  damage-force-1hp: true
  slaying: false
  shearing-sheep: true
  shearing-mushroomcow: nonowner
  filling-cow: true
  filling-mushroomcow: true
  pushing: false
  environment-damaging: true
  monster-damaging: true
  breeding: true
  dropping-items: true

enabled-entities:
  Chicken: true
  Cow: true
  MushroomCow: true
  Pig: true
  Sheep: true
  Wolf: true
  Ozelot: true
  
protect-environment:
  set-owner-when-breeding-natural: true
  extinction:
    respawn-delay: 600
    # Animals will respawn on this blocks.
    respawn-blocks: [2, 110, 18]
    # If it can't find respawn-blocks, It will spawn on random place
    respawn-failsafe: false
    # Set animals respawning range.
    respawn-minrange: 30
    respawn-maxrange: 40
    
    # Set regen percent.
    # YOU MUST NOT SET `enviroment-died` to 1 UNLESS animal spawning is DISABLED
    # OR ANIMAL SPAWN TICK IS 0. IF NOT, ANIMALS WILL RULE THE WORLD
    player-died: 1
    enviroment-died: 0.5
    owner-set: 1

language:
  mobs:
    Chicken: 'Chicken'
    Cow: 'Cow'
    MushroomCow: 'Mooshroom'
    Pig: 'Pig'
    Sheep: 'Sheep'
    Wolf: 'Wolf'
    Ozelot: 'Cat'
  commands:
    addmember:
      help: 'Adds member of your animals in range.'
      usage: '<range> <player>, <player>, ...'
      finish: '&e{1} Animals were proccessed.'
    delmember:
      help: 'Deletes member of your animals in range.'
      usage: '<range> <player>, <player>, ...'
      finish: '&e{1} Animals were proccessed.'
    killrange:
      help: '&cKills your animal without drops in your range.'
      usage: '<range>'
      finish: '&e{1} Animals were proccessed.'
    killoutrange:
      help: '&cKills your animal without drops not in your range.'
      usage: '<range>'
      finish: '&e{1} Animals were proccessed.'
    kill:
      help: '&cKills all your animal without drops.'
      usage: ''
      finish: '&e{1} Animals were proccessed.'
    transfer:
      help: 'Transfers your animal permission to someone.'
      usage: '<player>'
      noplayer: '&cPlayer does not exist!'
      punch: '&ePunch your animals that you want to transfer!'
      selected: '&e{1} animals are selected. &f/ep transfer end&e to finish, &f/ep transfer cancel&e to cancel.'
      canceled: '&eTransfer canceled.'
      ended: '&eWait until other player agrees your animal transfer.'
      ready-animals: '&e{1} {2}'
      ready-ask: '&eWill be transfered. To accept, type &f/ep transfer accept&e, to deny type &f/ep transfer deny&e.'
      accepted: '&eTransfer successfully finished! You can breed {1} more animals.'
      denied: '&eTransfer cancelled.'
      noslot: '&eOther player doesn''t have slots left. He can breed {1} more animals.'
    killplayer:
      help: '&cKills all of player's animal without drops.'
      usage: '<player>'
      finish: '&e{1} Animals were proccessed.'
    killall:
      help: '&cKills all of owned animal without drops.'
      usage: ''
      finish: '&e{1} Animals were proccessed.'
    forceowner:
      help: '&cForces all animal to player in range.'
      usage: '<range> <player>'
      finish: '&e{1} Animals were proccessed.'
    help:
      help: 'Display this message.'
      usage: ''
      display-info: '&bEntityProtect &fversion {1}'
      display-help: '&e{1} &f - &b{2}'
      display-usage: '&aUsage: &e{1} {2}'
      player-only: 'Only in-game players can use this command.'
      permission: '&cYou don\'t have permission to do that!'
  console:
    breed-complete: '{1} breeded {2}, He can breed {3} more animals.'
    breed-fail: '{1} tried to breed {2}, but he doesn\'t have any slots left.'
    slay-animal: '{1} slayed {2}\'s {3}. {2} can breed {4} more animals.'
    natural-kill: 'Environment killed {1}\'s {2}. He can breed {3} more animals.'
  breed-more: '&bYou can breed {1} more animals.'
  owner-info: '&cThis {1}\'s Owner is &e{2}.'
  access-denied: '&cSorry, you can\'t do that.'
  you: 'You'
      
